services:
    ros2:
        build:
            context: .
            args:
                USER_UID: ${HOST_UID:-1000}
                USER_GID: ${HOST_GID:-1000}
                RENDER_GID: ${RENDER_GID:-992}
        image: ros2-humble
        container_name: ros2
        network_mode: host
        ipc: host
        stdin_open: true
        tty: true
        environment:
            - DISPLAY=${DISPLAY}
            - QT_X11_NO_MITSHM=1
            - QT_QPA_PLATFORM=xcb
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ..:/home/ros/ros2_ws
        devices:
            - /dev/dri:/dev/dri
        group_add:
            - video
            - "${RENDER_GID}"
